syntax = "proto3";

package file;
option go_package = "./";

// ----------- Service -----------

service FileService {
  // Клиент стримит файл (по частям), а сервер сохраняет его в MinIO
  rpc UploadFile (stream UploadFileRequest) returns (UploadFileResponse);

  // Клиент запрашивает 1 файл по ID, сервер отправляет его url для скачивания
  rpc GetFile (GetFileRequest) returns (GetFileResponse);

  // Клиент передаёт список ID, сервер отправляет urls для скачивания файлов
  rpc GetFiles (GetFilesRequest) returns (GetFilesResponse);

  // Удаляет один файл по ID
  rpc DeleteFile (DeleteFileRequest) returns (DeleteFileResponse);

  // Удаляет несколько файлов по списку ID
  rpc DeleteFiles (DeleteFilesRequest) returns (DeleteFileResponse);
}

// ----------- Requests -----------


message UploadFileRequest {
  string file_name = 1;
  bytes data = 2; // Содержимое файла (может приходить в нескольких чанках)
}

message GetFileRequest {
  string file_id = 1;
}

message GetFilesRequest {
  repeated string file_ids = 1;
}

message DeleteFileRequest {
  string file_id = 1;
}

message DeleteFilesRequest {
  repeated string file_ids = 1;
}

// ----------- Responses -----------

message UploadFileResponse {
  string file_id = 1;  // Уникальный ID, по которому можно получить файл
  string file_url = 2; // URL для доступа к файлу
  string message = 3;
}

message GetFileResponse {
  string file_url = 1; // URL для доступа к файлу
}

message GetFilesResponse {
  repeated string file_urls = 1; // Список URL для доступа к файлам
}

message DeleteFileResponse {
  string message = 1;
}